// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnyrJxnQQyPUty-G21-5dTeis4RR4SwWA',
    appId: '1:138747542255:web:4196cabab6d501e72b391a',
    messagingSenderId: '138747542255',
    projectId: 'smit-firebase-practice',
    authDomain: 'smit-firebase-practice.firebaseapp.com',
    storageBucket: 'smit-firebase-practice.appspot.com',
    measurementId: 'G-REFMX2VSBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwy0i81bw5TAmNeLC7jDU5SZak8jPMvFo',
    appId: '1:138747542255:android:1e1bc33f19527d2a2b391a',
    messagingSenderId: '138747542255',
    projectId: 'smit-firebase-practice',
    storageBucket: 'smit-firebase-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjVvp7jhgFrdzMTszu8i25ql7ClZDXkm0',
    appId: '1:138747542255:ios:25d750828fb252ab2b391a',
    messagingSenderId: '138747542255',
    projectId: 'smit-firebase-practice',
    storageBucket: 'smit-firebase-practice.appspot.com',
    iosBundleId: 'com.example.groceryOrderAppFlutter',
  );
}
